baseURL = '/ude-user-docs/api/'
locale = 'en-us'
title = 'UDE API Reference'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow HTML in Markdown if needed

[permalinks]
  api = "/:contentbasename/"
